name: Build and Deploy Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
  workflow_dispatch:

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN}}
  BRANCH_NAME: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Export Secrets
      #   run: |
      #     mkdir -p path/to/artifact
      #     echo ${{ secrets.PERSONAL_TOKEN }} | base64 -i > path/to/artifact/exported-secrets.env
      #     # Repeat the above line for each secret
      #     FILE_CONTENT=$(cat path/to/artifact/exported-secrets.env)
      #     echo "FILE_CONTENT=${FILE_CONTENT}" >> $GITHUB_ENV
    
      # - name: Encrypt secret and set as environment variable
      #   run: |
      #     echo ${{ secrets.PERSONAL_TOKEN }} | base64 -i >> /tmp/secrets.env
      #     TOKEN=$(cat /tmp/secrets.env)
      #     echo "PERSONAL_TOKEN=${TOKEN}" >> $GITHUB_ENV

      - name: Repository Dispatch
        # if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN}}
          repository: samah603/import-repo
          event-type: deploy
          client-payload: '{ "branch": "${{ env.BRANCH_NAME }}", "token": "${{ env.PERSONAL_TOKEN }}" }'
