name: Build and Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
     name: automate
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      BRANCH_NAME: ${{ vars.BRANCH_NAME }}
      EMAIL_USERNAME: ${{ vars.EMAIL_USERNAME }}
      #EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.PERSONAL_TOKEN }}
          repository: samah603/import-repo
          event-type: deploy
          client-payload: '{ "branch": "${{ env.BRANCH_NAME }}", "token": "${{ env.PERSONAL_TOKEN }}", "email_user": "${{ env.EMAIL_USERNAME }}", "email_pass": "${{ secrets.EMAIL_PASSWORD }}" }'
