name: Trigger Repo B Workflow

on:
  push:
    branches:
      - develop  # Adjust to your branch name

jobs:
  trigger_repo_b:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2

      - name: Trigger Repo B Workflow
        env:
          REPO_B_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer $REPO_B_TOKEN" \
            "https://api.github.com/repos/your-username/repo-b/dispatches" \
            -d '{"event_type": "trigger-repo-b", "client_payload": {"branch": "develop", "additional_key": "additional_value"}}'
