name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN}}
  BRANCH_NAME: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Repository Dispatch
        # if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN}}
          repository: samah603/import-repo
          event-type: deploy
          client-payload: '{ "branch": "${{ env.BRANCH_NAME }}", "token": "${{ env.PERSONAL_TOKEN }}" }'
